services:
    node:
        build:
            context: .
            target: ${MODE}
        environment:
            - NODE_ENV=${MODE}
            - PORT=${PORT}
        ports:
        - ${PORT}:${PORT}