name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -p 4531 -H 187.191.25.39 >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avz -e 'ssh -p 4531' public/ ambry@187.191.25.39:/home/ambry/
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: 187.191.25.39
          username: ambry
          password: arkus@123
          port: 4531
          script: ls -al